version: '3.8'
services:
  golang:
    container_name: ep_go
    build:
      context: docker/go
      target: dev
    volumes:
      - "./:/var/app"
    working_dir: "/var/app"
    command: [ "/bin/sh", "-c", "tail -f /dev/null" ]
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - INFLUXDB_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    restart: always
    depends_on:
      - influxdb
  influxdb:
    container_name: ep_influxdb
    image: influxdb:2.0
    env_file:
      - .env
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    container_name: ep_grafana
    build:
      context: docker/grafana
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - influxdb