{
 "title": "Endpoint Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Endpoints response time in millisecond.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"status\" and\n      r._field == \"TotalTime\"\n  )\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000 }))\n"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "timeseries",
   "description": "Endpoints 4xx Errors",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"status\" and\n      r._field == \"StatusCode\" and\n      r._value > 399 and r._value < 500\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n  |> yield(name: \"4xx-errors\")"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "timeseries",
   "description": "Endpoints 5xx Errors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"status\" and\n      r._field == \"StatusCode\" and\n      r._value > 499 and r._value < 600\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n  |> yield(name: \"5xx-errors\")"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "timeseries",
   "description": "Connection Error Count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"error\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n  |> yield(name: \"error_count\")"
    }
   ]
  }
 ]
}